name: 'Execução Manual - Automação Web'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências
        run: npm i

      - name: Instalando Cypress
        run: npm install -D cypress

      - name: Verificando versão do Cypress
        run: npm cypress --version

      - name: Testes E2E (end-to-end)
        run: npx cypress run 

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports
